# -*- coding: utf-8 -*-
"""SOD_YOLOv8_Colab_Notebook (9).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12z4yJnP_uxDhoT2mmnvzemSOW7ftFt4G

# SOD-YOLOv8: Small Object Detection for Autonomous Systems
**Paper:** SOD-YOLOv8 — Enhancing YOLOv8 for Small Object Detection in Aerial Imagery and Traffic Scenes  
**Journal:** MDPI Sensors, 2024 | **DOI:** 10.3390/s24196209  
**Dataset:** VisDrone2019 | **Platform:** Google Colab T4 GPU  
**Group:** [GROUP_NUMBER] | **Roll Numbers:** [ROLL_NO_1], [ROLL_NO_2]

## Cell 1 — Environment Setup
> After this cell finishes, go to **Runtime → Restart session**, then run from Cell 2.
"""

import subprocess, sys

# Force install numpy 1.26.4 into a priority path
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "--target=/usr/local/lib/python3.12/dist-packages",
                "--upgrade", "numpy==1.26.4"], check=True)

# Patch numpy.trapz back for compatibility
import importlib, types
import numpy as np
if not hasattr(np, "trapz"):
    np.trapz = np.trapezoid

!pip install -q "ultralytics==8.3.0" --no-deps
!pip install -q torch torchvision torchaudio
!pip install -q "opencv-python-headless==4.8.1.78"
!pip install -q pandas matplotlib seaborn albumentations pillow pyyaml scipy psutil
!nvidia-smi
print("Done. Now go to Runtime > Restart session, then run Cell 2.")

"""## Cell 2 — Imports"""

import os
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"]     = "disabled"

import numpy as np
# Patch removed numpy functions for ultralytics compatibility
if not hasattr(np, "trapz"):
    np.trapz = np.trapezoid
if not hasattr(np, "bool"):   np.bool   = bool
if not hasattr(np, "int"):    np.int    = int
if not hasattr(np, "float"):  np.float  = float
if not hasattr(np, "complex"):np.complex= complex
if not hasattr(np, "object"): np.object = object
if not hasattr(np, "str"):    np.str    = str

import cv2, yaml, json, shutil, random, time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from collections import defaultdict
from PIL import Image
import torch
from ultralytics import YOLO
from ultralytics import settings
settings.update({"wandb": False})
import warnings
warnings.filterwarnings("ignore")

SEED   = 42
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

print(f"NumPy   : {np.__version__}")
print(f"PyTorch : {torch.__version__}")
print(f"Device  : {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU     : {torch.cuda.get_device_name(0)}")
    print(f"VRAM    : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")
print("WandB   : disabled")

"""## Cell 3 — Download VisDrone2019 Dataset"""

DATASET_DIR = Path("/content/datasets/VisDrone")
DATASET_DIR.mkdir(parents=True, exist_ok=True)

URLS = [
    "https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-train.zip",
    "https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-val.zip",
    "https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-test-dev.zip",
]

for url in URLS:
    fname = DATASET_DIR / url.split("/")[-1]
    if not fname.exists():
        print(f"Downloading {fname.name}...")
        !wget -q --show-progress "{url}" -O "{fname}"
        !unzip -q "{fname}" -d "{DATASET_DIR}"
    else:
        print(f"{fname.name} already exists.")

print("Dataset ready.")

"""## Cell 4 — Convert VisDrone Annotations to YOLO Format
VisDrone format: `[x, y, w, h, score, class, truncation, occlusion]`  
YOLO format: `[class_id, x_center_norm, y_center_norm, w_norm, h_norm]`
"""

CLASS_NAMES = ["pedestrian","people","bicycle","car","van",
               "truck","tricycle","awning-tricycle","bus","motor"]

def visdrone_to_yolo(split_dir: Path):
    ann_dir   = split_dir / "annotations"
    img_dir   = split_dir / "images"
    label_dir = split_dir / "labels"
    label_dir.mkdir(exist_ok=True)
    count = 0
    for ann_file in sorted(ann_dir.glob("*.txt")):
        img_path = img_dir / (ann_file.stem + ".jpg")
        if not img_path.exists():
            continue
        img_w, img_h = Image.open(img_path).size
        lines = []
        for row in open(ann_file).readlines():
            p = row.strip().split(",")
            if len(p) < 8:
                continue
            x, y, w, h, _, cls = int(p[0]),int(p[1]),int(p[2]),int(p[3]),p[4],int(p[5])
            if cls == 0 or cls > 10 or w <= 0 or h <= 0:
                continue
            xc = max(0., min(1., (x + w/2) / img_w))
            yc = max(0., min(1., (y + h/2) / img_h))
            wn = max(0., min(1., w / img_w))
            hn = max(0., min(1., h / img_h))
            lines.append(f"{cls-1} {xc:.6f} {yc:.6f} {wn:.6f} {hn:.6f}")
        open(label_dir / ann_file.name, "w").write("\n".join(lines))
        count += 1
    return count

for split in ["VisDrone2019-DET-train", "VisDrone2019-DET-val", "VisDrone2019-DET-test-dev"]:
    p = DATASET_DIR / split
    if p.exists():
        n = visdrone_to_yolo(p)
        print(f"{split}: {n} files converted")

"""## Cell 5 — Exploratory Data Analysis"""

def analyze(split_dir):
    stats = {"class_counts": defaultdict(int), "areas": [],
             "objs_per_img": [], "small":0, "medium":0, "large":0, "total":0}
    for lf in (split_dir / "labels").glob("*.txt"):
        n = 0
        for line in open(lf).readlines():
            p = line.strip().split()
            if len(p) != 5: continue
            cls, w, h = int(p[0]), float(p[3]), float(p[4])
            area = w * h
            stats["class_counts"][CLASS_NAMES[cls]] += 1
            stats["areas"].append(area)
            stats["total"] += 1
            n += 1
            if area < 0.001:   stats["small"]  += 1
            elif area < 0.01:  stats["medium"] += 1
            else:              stats["large"]  += 1
        stats["objs_per_img"].append(n)
    return stats

train_dir = DATASET_DIR / "VisDrone2019-DET-train"
val_dir   = DATASET_DIR / "VisDrone2019-DET-val"
S = analyze(train_dir)

fig, axes = plt.subplots(2, 2, figsize=(16, 11))
fig.suptitle("VisDrone2019 — Exploratory Data Analysis", fontsize=15, fontweight="bold")

# Class distribution
ax = axes[0,0]
cls_names = list(S["class_counts"].keys())
cls_vals  = list(S["class_counts"].values())
bars = ax.barh(cls_names, cls_vals, color=plt.cm.Set2(np.linspace(0,1,10)))
ax.set_xlabel("Instances"); ax.set_title("Class Distribution", fontweight="bold")
ax.grid(axis="x", alpha=0.3)
[ax.text(b.get_width()+200, b.get_y()+b.get_height()/2, f"{v:,}", va="center", fontsize=8)
 for b,v in zip(bars,cls_vals)]

# Bounding box area
ax = axes[0,1]
ax.hist(np.array(S["areas"])*100, bins=100, color="steelblue", edgecolor="white", alpha=0.8)
ax.axvline(0.1, color="red", linestyle="--", linewidth=1.5, label="Small threshold")
ax.set_xlabel("BBox Area (% of image)"); ax.set_title("Bounding Box Area Distribution", fontweight="bold")
ax.set_xlim(0, 5); ax.legend(); ax.grid(alpha=0.3)

# Objects per image
ax = axes[1,0]
ax.hist(S["objs_per_img"], bins=50, color="coral", edgecolor="white", alpha=0.8)
mean_obj = np.mean(S["objs_per_img"])
ax.axvline(mean_obj, color="darkred", linestyle="--", linewidth=2, label=f"Mean={mean_obj:.1f}")
ax.set_xlabel("Objects per Image"); ax.set_title("Objects per Image", fontweight="bold")
ax.legend(); ax.grid(alpha=0.3)

# Size pie chart
ax = axes[1,1]
ax.pie([S["small"],S["medium"],S["large"]], explode=(0.05,0.05,0.05),
       labels=["Small\n(<0.1%)","Medium\n(0.1-1%)","Large\n(>1%)"],
       autopct="%1.1f%%", colors=["#FF6B6B","#FFE66D","#4ECDC4"],
       textprops={"fontsize":10})
ax.set_title("Object Size Distribution", fontweight="bold")

plt.tight_layout()
plt.savefig("/content/eda_analysis.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"Total images  : {len(S['objs_per_img']):,}")
print(f"Total objects : {S['total']:,}")
print(f"Avg obj/image : {mean_obj:.1f}")
print(f"Small objects : {S['small']:,} ({100*S['small']/S['total']:.1f}%)")

"""## Cell 6 — Sample Annotated Images"""

COLORS = [(255,56,56),(255,157,151),(255,112,31),(255,178,29),(207,210,49),
          (72,249,10),(146,204,23),(61,219,134),(26,147,52),(0,212,187)]

def draw_boxes(img_path, label_path):
    img = cv2.cvtColor(cv2.imread(str(img_path)), cv2.COLOR_BGR2RGB)
    H, W = img.shape[:2]
    if label_path.exists():
        for line in open(label_path).readlines():
            p = line.strip().split()
            if len(p) != 5: continue
            cls = int(p[0])
            xc,yc,w,h = float(p[1]),float(p[2]),float(p[3]),float(p[4])
            x1,y1 = int((xc-w/2)*W), int((yc-h/2)*H)
            x2,y2 = int((xc+w/2)*W), int((yc+h/2)*H)
            cv2.rectangle(img,(x1,y1),(x2,y2),COLORS[cls],1)
            cv2.putText(img,CLASS_NAMES[cls],(x1,max(y1-3,0)),
                        cv2.FONT_HERSHEY_SIMPLEX,0.35,COLORS[cls],1)
    return img

img_dir   = train_dir / "images"
label_dir = train_dir / "labels"
samples   = random.sample(list(img_dir.glob("*.jpg")), 6)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("VisDrone2019 — Sample Training Annotations", fontsize=14, fontweight="bold")
for ax, ip in zip(axes.flatten(), samples):
    ax.imshow(draw_boxes(ip, label_dir / (ip.stem+".txt")))
    ax.set_title(ip.name, fontsize=8); ax.axis("off")
plt.tight_layout()
plt.savefig("/content/sample_annotations.png", dpi=150, bbox_inches="tight")
plt.show()

"""## Cell 7 — Dataset YAML Configuration"""

yaml_path = "/content/VisDrone.yaml"
cfg = {
    "path":  "/content/datasets/VisDrone",
    "train": "VisDrone2019-DET-train/images",
    "val":   "VisDrone2019-DET-val/images",
    "test":  "VisDrone2019-DET-test-dev/images",
    "nc":    10,
    "names": CLASS_NAMES
}
with open(yaml_path, "w") as f:
    yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
print(open(yaml_path).read())

"""## Cell 8 — SOD-YOLOv8 Architecture Definition
Key modification: 4th detection head at P2 (160×160) for small object detection.
"""

SOD_YAML = """
nc: 10
scales:
  s: [0.33, 0.50, 1024]

backbone:
  - [-1, 1, Conv,  [64,  3, 2]]
  - [-1, 1, Conv,  [128, 3, 2]]
  - [-1, 3, C2f,   [128, True]]
  - [-1, 1, Conv,  [256, 3, 2]]
  - [-1, 6, C2f,   [256, True]]
  - [-1, 1, Conv,  [512, 3, 2]]
  - [-1, 6, C2f,   [512, True]]
  - [-1, 1, Conv,  [1024,3, 2]]
  - [-1, 3, C2f,   [1024,True]]
  - [-1, 1, SPPF,  [1024, 5]]

head:
  - [-1,    1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1,6],1, Concat,     [1]]
  - [-1,    3, C2f,        [512]]

  - [-1,    1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1,4],1, Concat,     [1]]
  - [-1,    3, C2f,        [256]]

  - [-1,    1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1,2],1, Concat,     [1]]
  - [-1,    3, C2f,        [128]]

  - [-1,    1, Conv,       [128, 3, 2]]
  - [[-1,15],1, Concat,    [1]]
  - [-1,    3, C2f,        [256]]

  - [-1,    1, Conv,       [256, 3, 2]]
  - [[-1,12],1, Concat,    [1]]
  - [-1,    3, C2f,        [512]]

  - [-1,    1, Conv,       [512, 3, 2]]
  - [[-1,9], 1, Concat,    [1]]
  - [-1,    3, C2f,        [1024]]

  - [[18,21,24,27], 1, Detect, [nc]]
"""

sod_yaml_path = "/content/sod_yolov8s.yaml"
with open(sod_yaml_path, "w") as f:
    f.write(SOD_YAML)
print("SOD-YOLOv8 architecture saved.")
print("Detection heads: P2(160x160), P3(80x80), P4(40x40), P5(20x20)")

"""## Cell 9 — Phase 1: Train Baseline YOLOv8s"""

baseline = YOLO("yolov8s.pt")

baseline.train(
    data         = yaml_path,
    epochs       = 50,
    imgsz        = 640,
    batch        = 16,
    device       = DEVICE,
    name         = "baseline_yolov8s",
    project      = "runs",
    optimizer    = "SGD",
    lr0          = 0.01,
    lrf          = 0.01,
    momentum     = 0.937,
    weight_decay = 0.0005,
    warmup_epochs= 3.0,
    mosaic       = 1.0,
    mixup        = 0.1,
    degrees      = 10.0,
    translate    = 0.1,
    scale        = 0.5,
    fliplr       = 0.5,
    patience     = 20,
    workers      = 4,
    seed         = SEED,
)

"""## Cell 10 — Phase 2: Train SOD-YOLOv8s"""

# Install/update dependencies
!pip install -U ultralytics -q

import torch
import os
from ultralytics import YOLO

# Memory optimization settings
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

# Configuration
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
sod_yaml_path = "/content/sod_yolov8s.yaml"  # Your custom model config
yaml_path = "/content/VisDrone.yaml"          # Your dataset config

# Load custom model architecture
sod_model = YOLO(sod_yaml_path)

# Load pretrained weights and transfer compatible layers
pretrained = YOLO("yolov8s.pt")
pre_state = pretrained.model.state_dict()
sod_state = sod_model.model.state_dict()
transferred = 0
for k in sod_state:
    if k in pre_state and sod_state[k].shape == pre_state[k].shape:
        sod_state[k] = pre_state[k]
        transferred += 1
sod_model.model.load_state_dict(sod_state)
print(f"Transferred {transferred} pretrained layers")

# Training with memory-optimized settings
sod_model.train(
    data=yaml_path,
    epochs=20,
    imgsz=416,              # Reduced from 640 to save memory
    batch=4,                # Reduced from 16 to avoid OOM
    device=DEVICE,
    name="sod_yolov8s",
    project="runs",
    optimizer="SGD",
    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3.0,
    mosaic=1.0,
    mixup=0.1,
    degrees=10.0,
    translate=0.1,
    scale=0.5,
    fliplr=0.5,
    patience=20,
    workers=2,              # Reduced from 4 to save CPU memory
    amp=True,               # Keep AMP enabled
    cache=False,            # Disable label caching to save RAM
    close_mosaic=10,
    seed=42,
    deterministic=True,
    val=True,
    plots=True,
)

import torch, shutil, os
from pathlib import Path
from ultralytics import YOLO

# Validation
print("Running validation...")
metrics = sod_model.val(data=yaml_path, imgsz=416, batch=4)
print(f"mAP@50    : {metrics.box.map50:.4f}")
print(f"mAP@50-95 : {metrics.box.map:.4f}")
print(f"Precision : {metrics.box.mp:.4f}")
print(f"Recall    : {metrics.box.mr:.4f}")

# Save to Google Drive
from google.colab import drive
drive.mount("/content/drive")

SAVE = "/content/drive/MyDrive/SOD_YOLOv8_Results"
os.makedirs(SAVE, exist_ok=True)

for run in ["sod_yolov8s", "baseline_yolov8s"]:
    w = f"runs/{run}/weights/best.pt"
    if Path(w).exists():
        shutil.copy(w, f"{SAVE}/{run}_best.pt")
        print(f"Saved: {run}_best.pt")

torch.cuda.empty_cache()
print("Done!")

from google.colab import drive
drive.mount('/content/drive')

"""## Cell 11 — Evaluate & Compare Both Models"""

baseline_best = YOLO("runs/baseline_yolov8s/weights/best.pt")
sod_best      = YOLO("runs/sod_yolov8s3/weights/best.pt")

b_val = baseline_best.val(data=yaml_path, imgsz=416, batch=4, device=DEVICE, verbose=False)
s_val = sod_best.val(     data=yaml_path, imgsz=416, batch=4, device=DEVICE, verbose=False)

def metrics(v):
    return {"mAP50": v.box.map50, "mAP50-95": v.box.map,
            "Precision": v.box.mp, "Recall": v.box.mr}

B = metrics(b_val)
S = metrics(s_val)

print(f"{'Metric':<15} {'Baseline':>12} {'SOD-YOLOv8':>13} {'Delta':>8}")
print("-"*52)
for m in ["mAP50","mAP50-95","Precision","Recall"]:
    d = S[m]-B[m]
    print(f"{m:<15} {B[m]:>12.4f} {S[m]:>13.4f} {d:>+8.4f}")

"""## Cell 12 — Training Curves"""

def load_csv(run):
    p = f"runs/{run}/results.csv"
    if Path(p).exists():
        df = pd.read_csv(p); df.columns = df.columns.str.strip(); return df
    return None

bdf = load_csv("baseline_yolov8s")
sdf = load_csv("sod_yolov8s")

plots = [
    ("train/box_loss",      "Box Loss (Train)"),
    ("train/cls_loss",      "Class Loss (Train)"),
    ("train/dfl_loss",      "DFL Loss (Train)"),
    ("metrics/mAP50(B)",    "mAP@50 (Val)"),
    ("metrics/mAP50-95(B)", "mAP@50-95 (Val)"),
    ("val/box_loss",        "Box Loss (Val)"),
]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("Training Curves: Baseline YOLOv8s vs SOD-YOLOv8s", fontsize=14, fontweight="bold")
for ax, (col, title) in zip(axes.flatten(), plots):
    if bdf is not None and col in bdf.columns:
        ax.plot(bdf["epoch"], bdf[col], color="#4A90D9", lw=2, label="Baseline")
    if sdf is not None and col in sdf.columns:
        ax.plot(sdf["epoch"], sdf[col], color="#E74C3C", lw=2, label="SOD-YOLOv8")
    ax.set_title(title, fontweight="bold"); ax.set_xlabel("Epoch")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("/content/training_curves.png", dpi=150, bbox_inches="tight")
plt.show()

"""## Cell 13 — Per-Class AP@50 Comparison"""

b_per = b_val.box.ap50
s_per = s_val.box.ap50

x = np.arange(len(CLASS_NAMES))
fig, ax = plt.subplots(figsize=(14, 6))
ax.bar(x-0.175, b_per, 0.35, label="Baseline YOLOv8s",    color="#4A90D9", alpha=0.85)
ax.bar(x+0.175, s_per, 0.35, label="SOD-YOLOv8s (Ours)",  color="#E74C3C", alpha=0.85)
ax.set_xticks(x); ax.set_xticklabels(CLASS_NAMES, rotation=30, ha="right")
ax.set_ylabel("AP@50"); ax.set_ylim(0,1)
ax.set_title("Per-Class AP@50: Baseline vs SOD-YOLOv8s", fontweight="bold")
ax.legend(); ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig("/content/per_class_ap.png", dpi=150, bbox_inches="tight")
plt.show()

for i, cls in enumerate(CLASS_NAMES):
    print(f"{cls:<18} baseline={b_per[i]:.4f}  sod={s_per[i]:.4f}  Δ={s_per[i]-b_per[i]:+.4f}")

"""## Cell 14 — Qualitative Detection Comparison"""

val_imgs = random.sample(list((DATASET_DIR/"VisDrone2019-DET-val"/"images").glob("*.jpg")), 4)

fig, axes = plt.subplots(4, 2, figsize=(18, 20))
fig.suptitle("Baseline YOLOv8s  vs  SOD-YOLOv8s\n(VisDrone2019 Validation)", fontsize=14, fontweight="bold")

for i, ip in enumerate(val_imgs):
    bp = baseline_best.predict(str(ip), imgsz=640, conf=0.25, device=DEVICE, verbose=False)[0]
    sp = sod_best.predict(     str(ip), imgsz=640, conf=0.25, device=DEVICE, verbose=False)[0]
    axes[i,0].imshow(cv2.cvtColor(bp.plot(line_width=1), cv2.COLOR_BGR2RGB))
    axes[i,0].set_title(f"Baseline — {len(bp.boxes)} detections", color="#4A90D9")
    axes[i,0].axis("off")
    axes[i,1].imshow(cv2.cvtColor(sp.plot(line_width=1), cv2.COLOR_BGR2RGB))
    axes[i,1].set_title(f"SOD-YOLOv8 — {len(sp.boxes)} detections", color="#E74C3C")
    axes[i,1].axis("off")

plt.tight_layout()
plt.savefig("/content/qualitative_results.png", dpi=150, bbox_inches="tight")
plt.show()

"""## Cell 15 — Inference Speed Benchmark"""

sample_img = str(val_imgs[0])

def benchmark(model, n=100, warmup=10):
    for _ in range(warmup):
        model.predict(sample_img, imgsz=640, device=DEVICE, verbose=False)
    times = []
    for _ in range(n):
        t0 = time.perf_counter()
        model.predict(sample_img, imgsz=640, device=DEVICE, verbose=False)
        times.append((time.perf_counter()-t0)*1000)
    return np.mean(times), 1000/np.mean(times)

b_ms, b_fps = benchmark(baseline_best)
s_ms, s_fps = benchmark(sod_best)
b_params = sum(p.numel() for p in baseline_best.model.parameters())/1e6
s_params = sum(p.numel() for p in sod_best.model.parameters())/1e6

print(f"{"Model":<20} {"Params(M)":>10} {"Latency(ms)":>13} {"FPS":>8}")
print("-"*55)
print(f"{"Baseline YOLOv8s":<20} {b_params:>10.1f} {b_ms:>13.2f} {b_fps:>8.1f}")
print(f"{"SOD-YOLOv8s":<20} {s_params:>10.1f} {s_ms:>13.2f} {s_fps:>8.1f}")

"""## Cell 16 — Performance Comparison Chart"""

metrics_list = ["mAP@50","mAP@50-95","Precision","Recall"]
b_vals = [B["mAP50"],B["mAP50-95"],B["Precision"],B["Recall"]]
s_vals = [S["mAP50"],S["mAP50-95"],S["Precision"],S["Recall"]]

x = np.arange(len(metrics_list))
fig, ax = plt.subplots(figsize=(11, 6))
bars1 = ax.bar(x-0.175, b_vals, 0.35, label="Baseline YOLOv8s",   color="#4A90D9", alpha=0.85)
bars2 = ax.bar(x+0.175, s_vals, 0.35, label="SOD-YOLOv8s (Ours)", color="#E74C3C", alpha=0.85)
for bar in list(bars1)+list(bars2):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
            f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=10)
ax.set_xticks(x); ax.set_xticklabels(metrics_list, fontsize=12)
ax.set_ylim(0,1); ax.set_ylabel("Score"); ax.legend(fontsize=11)
ax.set_title("Baseline YOLOv8s vs SOD-YOLOv8s — VisDrone2019 Val", fontweight="bold")
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig("/content/comparison_chart.png", dpi=150, bbox_inches="tight")
plt.show()

"""## Cell 17 — Final Results Summary"""

print("="*60)
print("  FINAL RESULTS — SOD-YOLOv8 on VisDrone2019")
print("="*60)
print(f"{"Model":<20} {"mAP@50":>8} {"mAP50-95":>10} {"Prec":>7} {"Rec":>7} {"FPS":>7}")
print("-"*60)
print(f"{"Baseline YOLOv8s":<20} {B["mAP50"]:>8.4f} {B["mAP50-95"]:>10.4f} {B["Precision"]:>7.4f} {B["Recall"]:>7.4f} {b_fps:>7.1f}")
print(f"{"SOD-YOLOv8s":<20} {S["mAP50"]:>8.4f} {S["mAP50-95"]:>10.4f} {S["Precision"]:>7.4f} {S["Recall"]:>7.4f} {s_fps:>7.1f}")
print("-"*60)
print(f"{"Improvement":<20} {S["mAP50"]-B["mAP50"]:>+8.4f} {S["mAP50-95"]-B["mAP50-95"]:>+10.4f} {S["Precision"]-B["Precision"]:>+7.4f} {S["Recall"]-B["Recall"]:>+7.4f}")
print("="*60)
print("\nSaved outputs:")
for f in ["/content/eda_analysis.png","/content/sample_annotations.png",
          "/content/training_curves.png","/content/per_class_ap.png",
          "/content/qualitative_results.png","/content/comparison_chart.png"]:
    print(f"  {f}")

# ── Imports ─────────────────────────────────────────────────────
from google.colab import files
from collections import Counter
import cv2, matplotlib.pyplot as plt
from ultralytics import YOLO
import torch

DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"
CLASS_NAMES = ["pedestrian","people","bicycle","car","van",
               "truck","tricycle","awning-tricycle","bus","motor"]

# ── Load models ─────────────────────────────────────────────────
baseline = YOLO("runs/baseline_yolov8s/weights/best.pt")
sod      = YOLO("runs/sod_yolov8s/weights/best.pt")

# ── Upload image ─────────────────────────────────────────────────
print("="*55)
print("  SOD-YOLOv8 LIVE DEMO — Upload a drone/traffic image")
print("="*55)
uploaded = files.upload()

for fname, data in uploaded.items():
    img_path = f"/content/{fname}"
    with open(img_path, "wb") as f:
        f.write(data)

    # ── Run inference ────────────────────────────────────────────
    b_res = baseline.predict(img_path, imgsz=640, conf=0.25,
                             device=DEVICE, verbose=False)[0]
    s_res = sod.predict(     img_path, imgsz=640, conf=0.25,
                             device=DEVICE, verbose=False)[0]

    # ── Side-by-side plot ────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(18, 8))
    fig.suptitle(f"Live Demo — {fname}", fontsize=14, fontweight="bold")

    axes[0].imshow(cv2.cvtColor(b_res.plot(line_width=2), cv2.COLOR_BGR2RGB))
    axes[0].set_title(f"Baseline YOLOv8s\n{len(b_res.boxes)} objects detected",
                    color="#4A90D9", fontweight="bold")
    axes[0].axis("off")

    axes[1].imshow(cv2.cvtColor(s_res.plot(line_width=2), cv2.COLOR_BGR2RGB))
    axes[1].set_title(f"SOD-YOLOv8s (Ours)\n{len(s_res.boxes)} objects detected",
                    color="#E74C3C", fontweight="bold")
    axes[1].axis("off")

    plt.tight_layout()
    plt.savefig(f"/content/demo_result_{fname}", dpi=150, bbox_inches="tight")
    plt.show()

    # ── Detection breakdown ──────────────────────────────────────
    print(f"\nBASELINE   — {len(b_res.boxes)} detections:")
    if len(b_res.boxes) > 0:
        b_cls = [CLASS_NAMES[int(c)] for c in b_res.boxes.cls.tolist()]
        for cls, n in sorted(Counter(b_cls).items(), key=lambda x: -x[1]):
            print(f"  {cls:20}: {n}")

    print(f"\nSOD-YOLOv8 — {len(s_res.boxes)} detections:")
    if len(s_res.boxes) > 0:
        s_cls = [CLASS_NAMES[int(c)] for c in s_res.boxes.cls.tolist()]
        for cls, n in sorted(Counter(s_cls).items(), key=lambda x: -x[1]):
            print(f"  {cls:20}: {n}")

    diff = len(s_res.boxes) - len(b_res.boxes)
    if diff > 0:
        print(f"\nSOD-YOLOv8 detected {diff} MORE objects than baseline.")
    else:
        print(f"\nBoth models detected similar number of objects.")
    print(f"Result saved: /content/demo_result_{fname}")

"""## Cell 18 — Save to Google Drive"""

from google.colab import drive
drive.mount("/content/drive")

SAVE = "/content/drive/MyDrive/SOD_YOLOv8_Results"
os.makedirs(SAVE, exist_ok=True)

for p in ["eda_analysis","sample_annotations","training_curves",
          "per_class_ap","qualitative_results","comparison_chart"]:
    src = f"/content/{p}.png"
    if Path(src).exists():
        shutil.copy(src, SAVE)

for run in ["baseline_yolov8s","sod_yolov8s"]:
    w = f"runs/{run}/weights/best.pt"
    if Path(w).exists():
        shutil.copy(w, f"{SAVE}/{run}_best.pt")

print(f"All results saved to {SAVE}")